version: '3'
services:
  database:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdojo
      MYSQL_USER: root
    ports:
      - 3306:3306
    volumes:
      - microservices-course-data:/var/lib/mysql
    container_name: microservices-database
volumes:
  microservices-course-data:


