spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: course
          uri: lb://course
          predicates:
            - Path=/course/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
  main:
    web-application-type: reactive
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true


