server:
  port: 8080

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver



